/**
 * 개발 및 테스트용 샘플(데모) 데이터
 * 모든 데이터는 명확히 [DEMO]로 표기되어 실제 데이터와 구분됩니다.
 */

import { CustomerRequest } from '@/types/customer';
import { Contract, ContractVersion } from '@/types/contract';
import { CONTRACT_POLICY_CONFIG } from './contractPolicy';

export const DEMO_REQUESTS: CustomerRequest[] = [
  {
    id: 'demo-req-001',
    request_number: 'DEMO-REQ-20270417-A1',
    type: 'application',
    status: 'contracted',
    customer_name: '신랑 김민수 / 신부 이서연',
    contact_type: 'phone',
    contact_value: '010-9876-5432',
    groom_name: '김민수',
    groom_phone: '010-1234-5678',
    bride_name: '이서연',
    bride_phone: '010-9876-5432',
    customer_email: 'wedding.seoyeon@example.com',
    wedding_date: '2027-04-17',
    is_date_undecided: false,
    wedding_time: '14:00',
    venue: '더채플앳청담',
    is_venue_undecided: false,
    hall_name: '커스티아홀',
    makeup_venue: '알루 청담본점',
    makeup_out_time: '12:00',
    groom_family_members: '부모님, 형',
    bride_family_members: '부모님, 여동생',
    product_id: 'album_plus',
    selected_option_ids: ['pyebaek'],
    selected_discount_ids: ['sunday', 'portfolio'],
    portfolio_agreed: true,
    mate_discount_info: '270417_김철수',
    shooting_requests: '본식 전 원판 촬영과 자연스러운 하객 스냅 위주로 요청드립니다.',
    retouch_requests: '피부 톤 화사하고 투명하게, 팔 라인 자연스러운 정리 부탁드립니다.',
    customer_note: '[DEMO 샘플] 본식 전 원판 촬영과 자연스러운 하객 스냅 위주로 요청드립니다.',
    terms_agreed: true,
    review: {
      reviewed_at: '2026-09-22T09:00:00Z',
      reviewed_by: '한민규 대표',
      is_available: true,
      availability_note: '해당 일정 대표 촬영 배정 가능합니다.',
      confirmed_product_id: 'album_plus',
      confirmed_option_ids: ['pyebaek'],
      confirmed_discount_ids: ['sunday', 'portfolio'],
      final_price: 1350000,
      deposit_amount: 300000,
      admin_memo: '[DEMO] 대표 직접 진행 예정 건 (알루 아웃 12시 확인)',
    },
    created_at: '2026-09-20T08:30:00Z',
    updated_at: '2026-09-20T09:00:00Z',
  },
  {
    id: 'demo-req-002',
    request_number: 'DEMO-REQ-20270523-B2',
    type: 'inquiry',
    status: 'new',
    customer_name: '신부 박지현',
    contact_type: 'kakao',
    contact_value: 'jihyun_wedding',
    groom_name: '',
    groom_phone: '',
    bride_name: '박지현',
    bride_phone: '010-3333-7777',
    customer_email: 'jihyun@example.com',
    wedding_date: '2027-05-23',
    is_date_undecided: false,
    wedding_time: '12:30',
    venue: '빌라드지디 수서',
    is_venue_undecided: false,
    hall_name: '르씨엘홀',
    makeup_venue: '정샘물 이스트',
    makeup_out_time: '10:30',
    groom_family_members: '부모님',
    bride_family_members: '부모님, 오빠',
    product_id: 'standard',
    selected_option_ids: ['makeup', 'second_shooter'],
    selected_discount_ids: ['sunday'],
    portfolio_agreed: false,
    shooting_requests: '메이크업 샵부터 동행하는 2인 촬영 가능 여부 문의드립니다.',
    customer_note: '[DEMO 샘플] 메이크업 샵부터 동행하는 2인 촬영 가능 여부 문의드립니다.',
    terms_agreed: true,
    created_at: '2026-09-20T09:15:00Z',
    updated_at: '2026-09-20T09:15:00Z',
  },
];

export const DEMO_CONTRACTS: Contract[] = [
  {
    id: 'cnt_mock_001',
    request_id: 'demo-req-001',
    contract_number: 'DM-CTR-20270417-001',
    access_token: 'demo-token',
    status: 'sent',
    active_version_id: 'ver_mock_001_v1',
    created_at: '2026-09-22T09:30:00Z',
    updated_at: '2026-09-22T09:30:00Z',
  },
];

export const DEMO_CONTRACT_VERSIONS: ContractVersion[] = [
  {
    id: 'ver_mock_001_v1',
    contract_id: 'cnt_mock_001',
    version_number: 1,
    terms_version: CONTRACT_POLICY_CONFIG.version,
    is_active: true,
    created_at: '2026-09-22T09:30:00Z',
    snapshot: {
      contract_number: 'DM-CTR-20270417-001',
      customer_name: '신랑 김민수 / 신부 이서연',
      customer_contact: '010-9876-5432 (phone)',
      groom_name: '김민수',
      groom_phone: '010-1234-5678',
      bride_name: '이서연',
      bride_phone: '010-9876-5432',
      customer_email: 'wedding.seoyeon@example.com',
      wedding_date: '2027-04-17',
      wedding_time: '14:00',
      venue: '더채플앳청담',
      hall_name: '커스티아홀',
      makeup_venue: '알루 청담본점',
      makeup_out_time: '12:00',
      groom_family_members: '부모님, 형',
      bride_family_members: '부모님, 여동생',
      mate_discount_info: '270417_김철수',
      shooting_requests: '본식 전 원판 촬영과 자연스러운 하객 스냅 위주로 요청드립니다.',
      retouch_requests: '피부 톤 화사하고 투명하게, 팔 라인 자연스러운 정리 부탁드립니다.',
      product_name: '화보형 (앨범 3권)',
      product_base_price: 1450000,
      product_included_items: [
        '대표 1인 촬영 (신부대기실 ~ 본식 ~ 원판 ~ 연회장)',
        '전체 원본 고화질 JPG 이메일 제공 (2,500장 이상, 장축 3,000px)',
        '정밀 보정본 80장 제공',
        '최고급 화보형 부부앨범 15x12 80p 1권 (신랑신부용)',
        '양가 부모님용 압축앨범 12x8 40p 2권 (선물용)',
      ],
      product_original_count: '2,500장 이상 (장축 3,000px)',
      product_retouched_count: 80,
      product_album_spec: '부부 화보형 80p 1권 + 양가 부모님 압축 40p 2권',
      options: [
        {
          name: '폐백 촬영 추가',
          price: 100000,
          description: '전통 폐백 진행 시 수모비 별도, 폐백실 연출 및 친인척 촬영',
        },
      ],
      discounts: [
        {
          name: '일요일 / 비수기 예식 할인',
          price: 100000,
          description: '일요일 또는 비수기 예식 진행 고객 대상',
        },
        {
          name: '포트폴리오 공개 동의 혜택',
          price: 100000,
          description: '디어메모리 웹사이트 및 인스타그램 포트폴리오 활용 동의 시',
        },
      ],
      total_base_price: 1450000,
      total_options_price: 100000,
      total_discount_amount: 200000,
      final_total_price: 1350000,
      deposit_amount: 300000,
      balance_amount: 1050000,
      shooting_scope: '신부대기실 ~ 본식 ~ 원판 ~ 연회장 / 폐백실',
      delivery_schedule: '전달 기준 1개월 보관 / 앨범 수령 1주일 이내 수정 요청',
      terms: {
        version: CONTRACT_POLICY_CONFIG.version,
        title: '디어메모리 본식스냅 계약 약관 (13개 조항)',
        deposit_terms: '신청 후 24시간 이내 300,000원 입금. 입금 후 72시간 이내 취소 시 전액 환불, 72시간 이후 환불 불가.',
        balance_terms: '최소 서비스 제공일 1주 이전 잔금 전액 완납.',
        delivery_terms: '전체 원본/보정본은 JPG 장축 3,000px 이메일 제공. 전달일 기준 1개월만 보관.',
        cancellation_refund_terms: '촬영 확정일 90일 이전(계약금 위약금), 60~90일(50%), 30~60일(70%), 30일 내(80%).',
        portfolio_terms: '포트폴리오 동의 시 dearmemory.co.kr, 블로그, 인스타그램에 사진이 품격 있게 소개될 수 있습니다.',
        copyright_terms: '저작권은 신랑신부님과 디어메모리가 공동 소유하며, 초상권은 신랑신부님의 권한입니다.',
        all_terms_text: CONTRACT_POLICY_CONFIG.sections.map((s) => `${s.title}\n${s.content}`).join('\n\n'),
      },
    },
  },
];
